version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        ports:
            - "8080:80" # Acesso ao servidor na porta 8080
        volumes:
            - .:/var/www/html
        networks:
            - laravel_network
        environment:
            - APP_ENV=local
            - APP_KEY=${APP_KEY} # Use variáveis de ambiente para segurança
            - DB_CONNECTION=mysql
            - DB_HOST=your_mysql_server_ip_or_hostname # Aqui você coloca o IP ou hostname do seu servidor MySQL
            - DB_PORT=3306 # A porta do seu MySQL
            - DB_DATABASE=time_capsule # Nome do banco de dados
            - DB_USERNAME=$DB_USERNAME} # Usuário do seu MySQL
            - DB_PASSWORD=${DB_PASSWORD} # Senha do seu MySQL

# Removido o serviço db, pois estamos usando o MySQL externo

volumes:
    dbdata:
        driver: local

networks:
    laravel_network:
        driver: bridge
