version: "3.8"

services:
    # Serviço PHP
    php:
        build:
            context: . # Direciona para o diretório onde está o Dockerfile
            dockerfile: Dockerfile
        volumes:
            - .:/var/www # Mapeia o diretório do projeto para o contêiner
        networks:
            - app-network

    # Serviço do Nginx
    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www # Mapeia o diretório do projeto para o contêiner
        ports:
            - "80:80"
        networks:
            - app-network
        depends_on:
            - php

    # Serviço MySQL (opcional)
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_password
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:

volumes:
    mysql_data:
