version: "3.8"

services:
    # Serviço do PHP
    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/var/www
        networks:
            - app-network

    # Serviço do Nginx
    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www
        ports:
            - "80:80"
        networks:
            - app-network
        depends_on:
            - php

    # Serviço do MySQL (opcional, caso precise de banco de dados)
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_password
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app-network

    # Serviço para o Composer
    composer:
        image: composer:2
        volumes:
            - ./src:/var/www
        working_dir: /var/www
        networks:
            - app-network

networks:
    app-network:

volumes:
    mysql_data:
