version: '3.8'

services:
  # Serviço do PHP-FPM
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel-network
    depends_on:
      - db
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    command: /usr/local/bin/start.sh

  # Serviço do Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www
    ports:
      - "80:80"
    networks:
      - laravel-network
    depends_on:
      - app

  # Serviço do MySQL (opcional, caso você esteja usando banco de dados)
  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  db-data:
    driver: local
