version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        ports:
            - "8080:80" # Acesso ao servidor na porta 8080
        volumes:
            - .:/var/www/html
        networks:
            - laravel_network
        environment:
            - APP_ENV=local
            - APP_KEY=base64:chaveAletoriaAqui
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=secret

    db:
        image: mysql:5.7
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel_network

volumes:
    dbdata:
        driver: local

networks:
    laravel_network:
        driver: bridge
